### ISSUE TITLE
Simplify routes configuration when webpack issue is resolved.

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#108]
There is a logged issue with webpack: https://github.com/webpack/webpack/issues/3065

When this is resolved we can greatly simplify our code-splitting async routes configuration.

**Comment by ctrlplusb** [comment]
Previous issues with related content:
#104 
#107

**Comment by ctrlplusb** [comment]
Sorted!  This was not an issue with webpack, but rather my configuration.  An enlightening experience to say the least.

**Comment by BerndWessels** [comment]
@ctrlplusb great work.

I got a clean new clone of `master` and it seems to work well now.

Only I still see some odd things like:
`[HMR] unexpected require(706) from disposed module 120`
and

	C:\react-universally>npm run development

	> react-universally@5.1.0 development C:\react-universally
	> node ./tools/development/server

	==> ℹ️  Creating webpack "client" config in "development" mode
	==> ℹ️  Creating webpack "server" config in "development" mode
	==> �  CLIENT -> ✅  Running
	==> �  CLIENT -> ✅  Built
	webpack built 48e8e9e8468a6f75e993 in 11635ms
	==> �  SERVER -> ✅  Built
	==> �  HTTP Listener is running on port 1337
	==> �  SERVER -> �  Running on http://localhost:1337
	webpack building...
	==> �  CLIENT -> ✅  Built
	webpack built e81d7dc4017b969179c1 in 1930ms
	webpack building...
	==> �  CLIENT -> ✅  Built
	webpack built a472b24bc4d1214ff25b in 1829ms
	==> �  SERVER -> ✅  Built
	==> �  SERVER -> �  Bundle invalid, check console for error
	C:\react-universally\build\server\main.js:1010
	/***/ null:
			  ^
	SyntaxError: Unexpected token :
		at Object.exports.runInThisContext (vm.js:76:16)
		at Module._compile (module.js:528:28)
		at Object.Module._extensions..js (module.js:565:10)
		at Module.load (module.js:473:32)
		at tryModuleLoad (module.js:432:12)
		at Function.Module._load (module.js:424:3)
		at Module.require (module.js:483:17)
		at require (internal/module.js:20:19)
		at new HotServer (C:\react-universally\tools\development\server.js:85:24)
		at Compiler.serverCompiler.plugin (C:\react-universally\tools\development\server.js:269:27)
	==> �  SERVER -> ✅  Built
	==> �  SERVER -> �  Bundle invalid, check console for error
	C:\react-universally\build\server\main.js:1010
	/***/ null:
			  ^
	SyntaxError: Unexpected token :
		at Object.exports.runInThisContext (vm.js:76:16)
		at Module._compile (module.js:528:28)
		at Object.Module._extensions..js (module.js:565:10)
		at Module.load (module.js:473:32)
		at tryModuleLoad (module.js:432:12)
		at Function.Module._load (module.js:424:3)
		at Module.require (module.js:483:17)
		at require (internal/module.js:20:19)
		at new HotServer (C:\react-universally\tools\development\server.js:85:24)
		at Compiler.serverCompiler.plugin (C:\react-universally\tools\development\server.js:269:27)

**Comment by ctrlplusb** [comment]
Hi @BerndWessels - things are flaky I agree.  It seems to have gotten worse over time.  I've had to consider a big restructure in order to provide us with better separation of concerns and guarantees that will make this easier for me to stabilise.

You can track progress here #109
