### ISSUE TITLE
npm run flow:remove is missing a dependency

### ISSUE THREAD

**Issue by alinporumb** [ctrlplusb/react-universally#152]
When running "npm run flow:remove" i get this error:

Error: Cannot find module 'recursive-readdir'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alin/Sites/react-universally/tools/flow/removeTypes.js:1:81)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

**Comment by ctrlplusb** [comment]
Good spot, thanks. I will prefer to replace this with `glob` as it I s being used in the development server.

**Comment by ctrlplusb** [comment]
Thanks again @alinporumb  😊
