### ISSUE TITLE
[koa2] Doesn't run.

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-universally#246]
> TypeError: middleware must be a function!
    at Application.use (/Users/sean/Development/ctrlplusb/react-universally/node_modules/koa/lib/application.js:106:41)
    at Object.module.exports.module.exports (/Users/sean/Development/ctrlplusb/react-universally/build/server/webpack:/src/server/index.js:26:5)
    at __webpack_require__ (/Users/sean/Development/ctrlplusb/react-universally/build/server/webpack:/webpack/bootstrap ec783651e8f6b9cdb740:19:1)
    at Object.<anonymous> (/Users/sean/Development/ctrlplusb/react-universally/build/server/index.js:2142:18)
    at __webpack_require__ (/Users/sean/Development/ctrlplusb/react-universally/build/server/webpack:/webpack/bootstrap ec783651e8f6b9cdb740:19:1)
    at /Users/sean/Development/ctrlplusb/react-universally/build/server/webpack:/webpack/bootstrap ec783651e8f6b9cdb740:65:1
    at Object.<anonymous> (/Users/sean/Development/ctrlplusb/react-universally/build/server/index.js:70:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by strues** [comment]
Pushing the fix right now.
