### ISSUE TITLE
Doesnt deploy

### ISSUE THREAD

**Issue by bradennapier** [ctrlplusb/react-universally#308]
Tried the 4 easy steps and got a bunch of errors.  Haven't read it in depth yet but just thought I would post since I am guessing this should have "just worked."  -- Thanks for this boilerplate though, looks like it should help a lot!

```
>   COPY Release/.node
> make: Leaving directory '/home/nowuser/src/node_modules/f11591077d80dde47978baad7caa7fb6f18c95b6/build'
> gyp info ok 
> node-pre-gyp info ok 
> gyp info spawn make
> make: Entering directory '/home/nowuser/src/node_modules/f11591077d80dde47978baad7caa7fb6f18c95b6/build'
>   SOLINK_MODULE(target) Release/obj.target/.node
> ▲ npm run build
>     index.js  77.9 kB       0  [emitted]  index
> index.js.map    91 kB       0  [emitted]  index
> chunk    {0} index.js, index.js.map (index) 59.5 kB [entry] [rendered]
>     [0] ./config/index.js 14.7 kB {0} [built]
>     [1] external "path" 42 bytes {0} [not cacheable]
>     [2] external "app-root-dir" 42 bytes {0} [not cacheable]
>     [5] external "express" 42 bytes {0} [not cacheable]
>     [6] ./~/997203da589ae7a363d73e219b6ff4e08b123864/register.js 25 bytes {0} [built]
>     [7] ./src/server/index.js 2.16 kB {0} [built]
>     [8] ./~/997203da589ae7a363d73e219b6ff4e08b123864/source-map-support.js 16.1 kB {0} [bu>    [16] ./src/server/middleware/reactApplication/index.js 3.72 kB {0} [built]
>    [17] ./src/server/middleware/security.js 4.32 kB {0} [built]
>    [18] ./src/server/middleware/serviceWorker.js 411 bytes {0} [built]
>    [18] ./src/server/middleware/serviceWorker.js 411 bytes {0} [built]
>    [23] external "compression" 42 bytes {0} [not cacheable]
>    [36] multi index 40 bytes {0} [built]
>    [23] external "compression" 42 bytes {0} [not cacheable]
>    [36] multi index 40 bytes {0} [built]
>      + 22 hidden modules
> ERROR in ./src/shared/components/DemoApp/DemoApp.js
>    [36] multi index 40 bytes {0} [built]
>      + 22 hidden modules
> ERROR in ./src/shared/components/DemoApp/DemoApp.js
> Module build failed: Error: channel closed
>     at ChildProcess.target.send (internal/child_process.js:540:16)
>      + 22 hidden modules
> ERROR in ./src/shared/components/DemoApp/DemoApp.js
> Module build failed: Error: channel closed
>     at ChildProcess.target.send (internal/child_process.js:540:16)
>     at Object.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyThread.js:138:10)
> ERROR in ./src/shared/components/DemoApp/DemoApp.js
> Module build failed: Error: channel closed
>     at ChildProcess.target.send (internal/child_process.js:540:16)
>     at Object.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyThread.js:138:10)
>     at Object.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f37> Module build failed: Error: channel closed
>     at ChildProcess.target.send (internal/child_process.js:540:16)
>     at Object.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyThread.js:138:10)
>     at Object.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyThreadPool.js:72:14)
>     at ChildProcess.target.send (internal/child_process.js:540:16)
>     at Object.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyThread.js:138:10)
>     at Object.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyThreadPool.js:72:14)
>     at HappyPlugin.compileAndUpdateCache (/home/nowuser/src/node_modules/af752f12b5555854d>     at Object.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyThread.js:138:10)
>     at Object.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyThreadPool.js:72:14)
>     at HappyPlugin.compileAndUpdateCache (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyPlugin.js:345:14)
>     at Object.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyThreadPool.js:72:14)
>     at HappyPlugin.compileAndUpdateCache (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyPlugin.js:345:14)
>     at HappyPlugin.compileInBackground (/home/nowuser/src/node_modules/af752f12b5555854d1b>     at HappyPlugin.compileAndUpdateCache (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyPlugin.js:345:14)
>     at HappyPlugin.compileInBackground (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyPlugin.js:314:25)
>     at HappyPlugin.compileInBackground (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyPlugin.js:314:25)
>     at HappyPlugin.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f7>     at HappyPlugin.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyPlugin.js:239:32)
>     at Object.HappyLoader (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f75>         home-08f918a0661fa31dfaf1.js  657 bytes       1  [emitted]  home
>        index-204a7f37e2a32a9813d2.js     231 kB       2  [emitted]  index
>       index-204a7f37e2a32a9813d2.css    2.54 kB       2  [emitted]  index
>   index-204a7f37e2a32a9813d2.css.map  107 bytes       2  [emitted]  index
>                         offline.html    2.04 kB          [emitted]  
>                                sw.js    8.78 kB          [emitted]  
> chunk    {0} about-0e89dbf3d1f83bbf1929.js (about) 1.95 kB {2} [rendered]
> chunk    {0} about-0e89dbf3d1f83bbf1929.js (about) 1.95 kB {2} [rendered]
>   [245] ./src/shared/components/DemoApp/About/index.js 34 bytes {0} [built]
>   [245] ./src/shared/components/DemoApp/About/index.js 34 bytes {0} [built]
>   [247] ./src/shared/components/DemoApp/About/About.js 1.44 kB {0} [built]
>   [247] ./src/shared/components/DemoApp/About/About.js 1.44 kB {0} [built]
>   [248] ./src/shared/components/DemoApp/About/Contributor/Contributor.js 432 bytes {0} [bu>   [248] ./src/shared/components/DemoApp/About/Contributor/Contributor.js 432 bytes {0} [built]
>   [249] ./src/shared/components/DemoApp/About/Contributor/index.js 40 bytes {0} [built]
> chunk    {1} home-08f918a0661fa31dfaf1.js (home) 698 bytes {2} [rendered]
>   [246] ./src/shared/components/DemoApp/Home/index.js 33 bytes {1} [built]
>   [250] ./src/shared/components/DemoApp/Home/Home.js 665 bytes {1} [built]
> chunk    {2} index-204a7f37e2a32a9813d2.js, index-204a7f37e2a32a9813d2.css, index-204a7f37>   [203] (webpack)/buildin/global.js 506 bytes {2} [built]
>   [207] ./src/client/components/ReactHotLoader.js 462 bytes {2} [built]
>   [208] ./src/client/registerServiceWorker.js 1.51 kB {2} [built]
>   [208] ./src/client/registerServiceWorker.js 1.51 kB {2} [built]
>   [218] ./src/shared/components/DemoApp/index.js 36 bytes {2} [built]
>   [244] multi index 40 bytes {2} [built]
>      + 230 hidden modules
>   [218] ./src/shared/components/DemoApp/index.js 36 bytes {2} [built]
>   [244] multi index 40 bytes {2} [built]
>      + 230 hidden modules
> Child __offline_serviceworker:
>   [244] multi index 40 bytes {2} [built]
>      + 230 hidden modules
> Child __offline_serviceworker:
>                       Asset     Size  Chunks  Chunk Names
>      + 230 hidden modules
> Child __offline_serviceworker:
>                       Asset     Size  Chunks  Chunk Names
>     __offline_serviceworker  7.19 kB       0  __offline_serviceworker
> Child __offline_serviceworker:
>                       Asset     Size  Chunks  Chunk Names
>     __offline_serviceworker  7.19 kB       0  __offline_serviceworker
>     chunk    {0} __offline_serviceworker (__offline_serviceworker) 16.2 kB [entry] [render>                       Asset     Size  Chunks  Chunk Names
>     __offline_serviceworker  7.19 kB       0  __offline_serviceworker
>     chunk    {0} __offline_serviceworker (__offline_serviceworker) 16.2 kB [entry] [rendered]
>         [0] ./~/99f0fbb4ffa4531978110b18b9ca92e56e4d8675/empty-entry.js 0 bytes {0} [built>     __offline_serviceworker  7.19 kB       0  __offline_serviceworker
>     chunk    {0} __offline_serviceworker (__offline_serviceworker) 16.2 kB [entry] [rendered]
>         [0] ./~/99f0fbb4ffa4531978110b18b9ca92e56e4d8675/empty-entry.js 0 bytes {0} [built]
>     chunk    {0} __offline_serviceworker (__offline_serviceworker) 16.2 kB [entry] [rendered]
>         [0] ./~/99f0fbb4ffa4531978110b18b9ca92e56e4d8675/empty-entry.js 0 bytes {0} [built]
>         [1] ./~/99f0fbb4ffa4531978110b18b9ca92e56e4d8675/lib/misc/sw-loader.js?json=%7B%22>         [0] ./~/99f0fbb4ffa4531978110b18b9ca92e56e4d8675/empty-entry.js 0 bytes {0} [built]
>         [1] ./~/99f0fbb4ffa4531978110b18b9ca92e56e4d8675/lib/misc/sw-loader.js?json=%7B%22data_var_name%22%3A%22__wpo%22%2C%22loaders%22%3A%5B%5D%2C%22cacheMaps%22%3A%5B%5D%7D!./~/99>         [1] ./~/99f0fbb4ffa4531978110b18b9ca92e56e4d8675/lib/misc/sw-loader.js?json=%7B%22data_var_name%22%3A%22__wpo%22%2C%22loaders%22%3A%5B%5D%2C%22cacheMaps%22%3A%5B%5D%7D!./~/99f0fbb4ffa4531978110b18b9ca92e56e4d8675/empty-entry.js 16.2 kB {0} [built]
> Child html-webpack-plugin for "offline.html":
> Child html-webpack-plugin for "offline.html":
>            Asset     Size  Chunks  Chunk Names
>            Asset     Size  Chunks  Chunk Names
>     offline.html  10.1 kB       0  
>     offline.html  10.1 kB       0  
>     chunk    {0} offline.html 6.31 kB [entry] [rendered]
>         [0] ./~/4e8f317e34f8060828b08c5ae281ad1a2a1b7544/lib/browser.js 114 bytes {0} [bui>     chunk    {0} offline.html 6.31 kB [entry] [rendered]
>         [0] ./~/4e8f317e34f8060828b08c5ae281ad1a2a1b7544/lib/browser.js 114 bytes {0} [built]
>         [1] ./tools/webpack/offlinePage/generate.js 2.3 kB {0} [built]
>         [0] ./~/4e8f317e34f8060828b08c5ae281ad1a2a1b7544/lib/browser.js 114 bytes {0} [built]
>         [1] ./tools/webpack/offlinePage/generate.js 2.3 kB {0} [built]
>         [2] ./~/199b080fc89f369d07fd641e8fe1e99eb1adadcd/index.js 3.42 kB {0} [built]
>         [1] ./tools/webpack/offlinePage/generate.js 2.3 kB {0} [built]
>         [2] ./~/199b080fc89f369d07fd641e8fe1e99eb1adadcd/index.js 3.42 kB {0} [built]
>         [3] external "util" 42 bytes {0} [not cacheable]
>         [2] ./~/199b080fc89f369d07fd641e8fe1e99eb1adadcd/index.js 3.42 kB {0} [built]
>         [3] external "util" 42 bytes {0} [not cacheable]
>         [4] ./~/d686cefc354f3e574c84ecc24d7b812b5d0a7650/lib/loader.js!./tools/webpack/offlinePage/index.js 433 bytes {0} [built]
>         [3] external "util" 42 bytes {0} [not cacheable]
>         [4] ./~/d686cefc354f3e574c84ecc24d7b812b5d0a7650/lib/loader.js!./tools/webpack/offlinePage/index.js 433 bytes {0} [built]
> Child extract-text-webpack-plugin:
>     chunk    {0} extract-text-webpack-plugin-output-filename 1.89 kB [entry] [rendered]
>         [4] ./~/d686cefc354f3e574c84ecc24d7b812b5d0a7650/lib/loader.js!./tools/webpack/offlinePage/index.js 433 bytes {0} [built]
> Child extract-text-webpack-plugin:
>     chunk    {0} extract-text-webpack-plugin-output-filename 1.89 kB [entry] [rendered]
>         [0] ./~/fefd448e2c8df7bfd1bfb8a632614271d09ec614/lib/css-base.js 1.51 kB {0} [built]
>         [1] ./~/fefd448e2c8df7bfd1bfb8a632614271d09ec614!./src/shared/components/DemoApp/globals.css 388 bytes {0} [built]
> Child extract-text-webpack-plugin:
>     chunk    {0} extract-text-webpack-plugin-output-filename 4.03 kB [entry] [rendered]
>         [0] ./~/fefd448e2c8df7bfd1bfb8a632614271d09ec614/lib/css-base.js 1.51 kB {0} [built]
>         [1] ./~/fefd448e2c8df7bfd1bfb8a632614271d09ec614!./~/5d5a0a4fd87b225e5cedfbfa6581eb510e8074a7/normalize.css 2.52 kB {0} [built]
> build exited with status 0
> ▲ npm start
> Error: Module build failed: Error: channel closed
>     at ChildProcess.target.send (internal/child_process.js:540:16)
>     at Object.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyThread.js:138:10)
>     at Object.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyThreadPool.js:72:14)
>     at HappyPlugin.compileAndUpdateCache (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyPlugin.js:345:14)
>     at HappyPlugin.compileInBackground (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyPlugin.js:314:25)
>     at HappyPlugin.compile (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyPlugin.js:239:32)
>     at Object.HappyLoader (/home/nowuser/src/node_modules/af752f12b5555854d1bb5a0342922f755f372340/lib/HappyLoader.js:34:15)
>     at Object.<anonymous> (/home/nowuser/src/build/server/index.js:1734:7)
>     at __webpack_require__ (/home/nowuser/src/build/server/webpack:/webpack/bootstrap 8e626c0f740cad9c26cc:19:1)
>     at Object.module.exports.module.exports.name (/home/nowuser/src/build/server/index.js:1741:67)
>     at __webpack_require__ (/home/nowuser/src/build/server/webpack:/webpack/bootstrap 8e626c0f740cad9c26cc:19:1)
>     at Object.<anonymous> (/home/nowuser/src/build/server/index.js:1486:85)
>     at __webpack_require__ (/home/nowuser/src/build/server/webpack:/webpack/bootstrap 8e626c0f740cad9c26cc:19:1)
>     at Object.<anonymous> (/home/nowuser/src/build/server/index.js:495:87)
>     at __webpack_require__ (/home/nowuser/src/build/server/webpack:/webpack/bootstrap 8e626c0f740cad9c26cc:19:1)
>     at Object.<anonymous> (/home/nowuser/src/build/server/index.js:1971:18)
>     at __webpack_require__ (/home/nowuser/src/build/server/webpack:/webpack/bootstrap 8e626c0f740cad9c26cc:19:1)
> Error Error: Command cross-env NODE_ENV=production node build/server ended with code 1
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> (node:277) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command cross-env NODE_ENV=production node build/server ended with code 1
> (node:277) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bradennapier** [comment]
I tried deploying with sudo and I got a different error:

```
> ▲ npm start
>     at bootstrap_node.js:509:3
> (node:276) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command cross-env NODE_ENV=production node build/server ended with code 1
> module.js:471
>     throw err;
>     ^
> Error: Cannot find module '/home/nowuser/src/build/server'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
> Error Error: Command cross-env NODE_ENV=production node build/server ended with code 1
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by ctrlplusb** [comment]
Hey @bradennapier!

Hmmm, this may have been a "temporary issue" with now.  I have experienced some random deploy failures at times.  Please make sure you have the latest now version installed.

I also noticed I am missing a step in the deploy process, specifically installing the project's dependencies! 😊

I have updated the docs accordingly.

Let me know how you get on.  😀

**Comment by ctrlplusb** [comment]
I gave this a try again and it seems okay.  Let me know if you continue experiencing this @bradennapier 

Closing for now.
