### ISSUE TITLE
Error in IE10

### ISSUE THREAD

**Issue by haddoq** [ctrlplusb/react-universally#450]
There seems to be a problem with IE10 both on local machine and on https://react-universally.now.sh/
Shouldn't the site work in IE10 with babel-env "last 2 versions" and polyfill.io?
Got these errors in the devtools console:

Error walking your react tree
TypeError: Unable to get property 'asyncComponents' of undefined or null reference
   {
      [functions]: ,
      __symbol:__symbol:react.element0.7163679959125997: undefined,
      __symbol:hasInstance0.71636799591259978: undefined,
      __symbol:isConcatSpreadable0.71636799591259979: undefined,
      __symbol:iterator0.71636799591259971: undefined,
      __symbol:match0.716367995912599710: undefined,
      __symbol:NaN0.71636799591259974: undefined,
      __symbol:NaN0.71636799591259976: undefined,
      __symbol:replace0.716367995912599711: undefined,
      __symbol:search0.716367995912599712: undefined,
      __symbol:species0.71636799591259972: undefined,
      __symbol:split0.716367995912599713: undefined,
      __symbol:toPrimitive0.716367995912599714: undefined,
      __symbol:toStringTag0.71636799591259977: undefined,
      __symbol:undef0.71636799591259973: undefined,
      __symbol:undef0.71636799591259975: undefined,
      __symbol:unscopables0.716367995912599715: undefined,
      description: "Unable to get property 'asyncComponents' of undefined or null reference",
      message: "Unable to get property 'asyncComponents' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to get property 'asyncComponents' of undefined or null reference
   at t (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:120829)
   at Anonymous function (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:216661)
   at s (https://cdn.polyfill.io/v2/polyfill.min.js?features=default,es6:3:14311)
   at n.exports (https://cdn.polyfill.io/v2/polyfill.min.js?features=default,es6:3:16834)
   at r (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:216028)
   at p (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:216277)
   at c (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:216486)
   at Anonymous function (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:216780)
   at s (https://cdn.polyfill.io/v2/polyfill.min.js?features=default,es6:3:14311)
   at n.exports (https://cdn.polyfill.io/v2/polyfill.min.js?features=default,es6:3:16834)"
   }

Uncaught (in promise) TypeError: Unable to get property 'asyncComponents' of undefined or null reference
   at t (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:120829)
   at _._constructComponentWithoutOwner (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:138355)
   at _._constructComponent (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:138219)
   at _.mountComponent (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:137406)
   at mountComponent (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:13407)
   at _.performInitialMount (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:139178)
   at _.mountComponent (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:137982)
   at mountComponent (https://react-universally.now.sh/client/index-aa82d9f216c877685074.js:1:13407)
   at _.performInitialMount (https://react-universally.now.sh/client/index-aa82d9

**Comment by strues** [comment]
Try adding Symbol to the polyfill.io include.

**Comment by haddoq** [comment]
Symbol is included via the es6 set. I think the problem is that the rendering of the client happens before the polyfill.io is loaded and ready. Maybe we could load the polyfills with a callback that start the render. https://polyfill.io/v2/polyfill.min.js?callback=polyfillsAreLoaded
