### ISSUE TITLE
npm run deploy error

### ISSUE THREAD

**Issue by Ancinek** [ctrlplusb/react-universally#475]
First of all, awesome work. I have been searching for an advanced boilerplate for a while and finally!
Everything is working great, but I am having problem on `npm run deploy`. This error keeps showing up (even if I just clone the repo and try to deploy):

```
npm install
> ✓ Using "package-lock.json"
> ⧗ Installing 72 main dependencies…
> ✓ Installed 1 module [4s]
> > react-universally@13.0.0 preinstall /home/nowuser/src
> > node internal/scripts/preinstall
> ▲ npm run build
> > react-universally@13.0.0 build /home/nowuser/src
> > babel-node internal/scripts/build --optimize
> sh: babel-node: not found
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! react-universally@13.0.0 build: `babel-node internal/scripts/build --optimize`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the react-universally@13.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2017-07-23T23_10_08_078Z-debug.log
> Error! The build step of your project failed. To retry, run `now --force`.
child_process.js:631
    throw err;
    ^

Error: Command failed: now
    at checkExecSyncError (child_process.js:588:13)
    at execSync (child_process.js:628:13)
    at exec (/Users/NYC/Desktop/JavaScript/Univ/internal/utils.js:40:3)
    at Object.<anonymous> (/Users/NYC/Desktop/JavaScript/Univ/internal/scripts/deploy.js:8:1)
    at Module._compile (module.js:569:30)
    at loader (/Users/NYC/Desktop/JavaScript/Univ/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/NYC/Desktop/JavaScript/Univ/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-universally@13.0.0 deploy: `babel-node internal/scripts/deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-universally@13.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/NYC/.npm/_logs/2017-07-23T23_10_10_259Z-debug.log
```

Any ideas?

**Comment by pebie** [comment]
Same issue here. Even by adding `babel-cli` and changing build commands to `./node-module/.bin/babel-node`

**Comment by Ancinek** [comment]
Seems like this is related to `babel-node` not being included as a dependency. But the thing is we should now use `babel-cli`

**Comment by ctrlplusb** [comment]
Sorry for the delay in looking at this. I will make some time this week 🤘

**Comment by designspin** [comment]
Hi, Any clues? I have this problem also!

**Comment by designspin** [comment]
@Ancinek , I just spotted your issue on Zeit Now repository, does not look like you got any solution from there?

**Comment by Ancinek** [comment]
@designspin - Sorry for the late response. No fix on that. They told be about installing babel-node in the dependencies but the babel-cli is already there.

**Comment by designspin** [comment]
@Ancinek - Yes it is. Well I am going to continue with my app development with the hope this can be resolved soon. If I find any resolution i'll be sure to post a solution.

**Comment by designspin** [comment]
@ctrlplusb - Hi, have you had a chance to take a look at this yet? If not, do you have any clues as to where I should start looking to resolve this?

**Comment by jlieb10** [comment]
#500
