### ISSUE TITLE
Snapshot test failing for `HomeRoute` and `AboutRoute`

### ISSUE THREAD

**Issue by oyeanuj** [ctrlplusb/react-universally#503]
Hey @ctrlplusb, I am seeing snapshot tests failing after [your latest commits](https://github.com/ctrlplusb/react-universally/commit/c27f2a9a7404ea5d2352e690db5b1f9e8311d2fc). I can reproduce it on a fresh install, so not sure if I am missing something.. but wanted to bring it to your notice anyway:

```sh
→ yarn test
yarn run v1.1.0
warning ../../package.json: No license field
$ jest
 FAIL  shared/components/DemoApp/AsyncHomeRoute/__tests__/HomeRoute.test.js
  ● <HomeRoute /> › renders

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

    @@ -1,8 +1,7 @@
     <div>
       <HelmetWrapper
    -    defer={true}
         encodeSpecialCharacters={true}
       >
         <title>
           Home
         </title>

      at Object.test (shared/components/DemoApp/AsyncHomeRoute/__tests__/HomeRoute.test.js:11:21)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)

 PASS  shared/components/DemoApp/Error404/__tests__/Error404.test.js
 FAIL  shared/components/DemoApp/AsyncAboutRoute/__tests__/AboutRoute.test.js
  ● <AboutRoute /> › renders

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

    @@ -4,11 +4,10 @@
           "textAlign": "center",
         }
       }
     >
       <HelmetWrapper
    -    defer={true}
         encodeSpecialCharacters={true}
       >
         <title>
           About
         </title>

      at Object.test (shared/components/DemoApp/AsyncAboutRoute/__tests__/AboutRoute.test.js:11:21)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
```

**Comment by jafri** [comment]
Same issue: `npm run prepush -- -u`  fixes it
