### ISSUE TITLE
Upgrading to babel-plugin-styled-components@1.5.0

### ISSUE THREAD

**Issue by declanelcocks** [ctrlplusb/react-universally#555]
Has anyone been able to deploy to `now` with `babel-plugin-styled-components@1.5.0`?

I'm running the `next` branch. I've upgraded all of the packages included in the repository, and everything runs perfectly (jest, eslint, now etc.). If I upgrade this package, it always fails during the build phase on `now` with the following error:

```
> WEBPACK: Creating an optimised bundle configuration for the "client"
> WEBPACK: Creating an optimised bundle configuration for the "server"
> HappyThread[0]: unable to send to worker! Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
>     at ChildProcess.target.send (internal/child_process.js:588:16)
>     at processSend (/home/nowuser/src/node_modules/happypack/lib/processSend.js:8:15)
>     at Object.UnbufferedFd.send (/home/nowuser/src/node_modules/happypack/lib/UnbufferedFd.js:9:3)
>     at send (/home/nowuser/src/node_modules/happypack/lib/HappyThread.js:38:20)
>     at Object.compile (/home/nowuser/src/node_modules/happypack/lib/HappyThread.js:146:7)
>     at Object.compile (/home/nowuser/src/node_modules/happypack/lib/HappyThreadPool.js:82:14)
>     at HappyPlugin.compile (/home/nowuser/src/node_modules/happypack/lib/HappyPlugin.js:192:14)
>     at Object.HappyLoader (/home/nowuser/src/node_modules/happypack/lib/HappyLoader.js:31:15)
>     at LOADER_EXECUTION (/home/nowuser/src/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
>     at runSyncOrAsync (/home/nowuser/src/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
>     at iterateNormalLoaders (/home/nowuser/src/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
>     at Array.<anonymous> (/home/nowuser/src/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
>     at Storage.finished (/home/nowuser/src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
>     at /home/nowuser/src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
>     at /home/nowuser/src/node_modules/graceful-fs/graceful-fs.js:78:16
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

I should point out that `npm run develop` also works, but for some reason `deploy` fails. I've spent quite some time looking into what could cause it, but found no answers, and even on the package's github there are no issues relating to this that I can see.

**Comment by ctrlplusb** [comment]
Closing this for now, please let me know if you found a solution. It may also be worth posting this kind of question on stackoverflow?
