### ISSUE TITLE
Server doesn't seem to get transpiled in the dev env

### ISSUE THREAD

**Issue by prewk** [ctrlplusb/react-universally#66]
Hi, cloned, installed, copied .env, and did `npm run development`:

```
Users/oskar/src/react-universally/tools/development/server.js:11
function createNotification(options = {}) {
                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
`` `

**Comment by prewk** [comment]
Wrong Node version ¯\_(ツ)_/¯
